num1 = int(input("enter the first number: "))
num2 = int(input("Enter the second number: "))
print("sum", num1 + num2)
print("difference", num1 - num2)
print("product", num1 * num2)
print("Quotient", num1 / num2)
